src/xr_embeds/urls.py
from django.urls import re_path

from xr_embeds.views import geojson_view, embed_html_view

app_name = "embeds"

urlpatterns = [
    re_path(r"^(\d+)/html/$", embed_html_view, name="embed_html"),
    re_path(
        r"^geojson/(?P<model_slug>\w+)/(?P<query_slug>\w+)/$",
        geojson_view,
        name="geojson_view",
    ),
]

src/xr_web/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from xr_wagtail.views import (
    remove_old_revisions_for_page,
    remove_old_revisions_for_all_pages,
)
from xr_embeds import urls as xr_embeds_urls
from xr_blog.views import RssFeed, AtomFeed

from . import webroot_redirects

urlpatterns = [
    re_path(
        r"^admin/pages/(\d+)/revisions/remove_old/$",
        remove_old_revisions_for_page,
        name="remove_old_revisions_for_page",
    ),
    re_path(
        r"^admin/remove_old_revisions/$",
        remove_old_revisions_for_all_pages,
        name="remove_old_revisions_for_all_pages",
    ),
    re_path(r"^embeds/", include(xr_embeds_urls)),
    path("feed/rss<int:feed_id>.xml", RssFeed(), name="blog-rss-feed"),
    path("feed/atom<int:feed_id>.xml", AtomFeed(), name="blog-atom-feed"),
    re_path(r"^django-admin/", admin.site.urls),
    re_path(r"^documents/", include(wagtaildocs_urls)),
    re_path(r"^admin/", include(wagtailadmin_urls)),
    re_path(r"", include(wagtail_urls)),
]


if settings.DEBUG or settings.TESTING:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    from django.views.defaults import server_error, page_not_found
    from django.http import Http404

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # Serve error pages
    urlpatterns = [
        path("500/", server_error),
        path("404/", page_not_found, {"exception": Http404()}),
    ] + urlpatterns

    # Serve static webroot files
    urlpatterns = webroot_redirects.urlpatterns + urlpatterns

src/xr_embeds/models.py
import logging

from django.db import models


logger = logging.getLogger(__name__)


class CachedImage(models.Model):
    image = models.ImageField(upload_to="cached_images")
    last_updated = models.DateTimeField(auto_now=True)
    original_url = models.URLField(unique=True)

src/xr_embeds/views.py
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.http import JsonResponse, Http404
from django.shortcuts import get_object_or_404
from django.utils.translation import ugettext as _
from wagtail.embeds.models import Embed

from xr_pages.models import LocalGroup


def embed_html_view(request, embed_id):
    embed = get_object_or_404(Embed, id=embed_id)

    data = {"embed_html": embed.html, "success": True}

    return JsonResponse(data)


def geojson_view(request, model_slug, query_slug):
    """GeoJson export for umap"""

    if model_slug == "local_group":
        model_queryset = LocalGroup.objects.exclude(is_regional_group=True)

        if query_slug == "all":
            model_queryset = model_queryset
        elif query_slug == "active":
            model_queryset = model_queryset.active()
        elif query_slug == "in_foundation":
            model_queryset = model_queryset.in_foundation()
        elif query_slug == "idle":
            model_queryset = model_queryset.idle()
        else:
            raise Http404()
    else:
        raise Http404()

    features = []

    for obj in model_queryset:
        if not (hasattr(obj, "lnglat") and obj.lnglat and "," in obj.lnglat):
            continue

        name = obj.name

        if obj.area_description:
            name = "{} {}".format(obj.name, obj.area_description)

        description = ""

        for attr_name in ["facebook", "twitter", "youtube", "instagram", "mastodon"]:
            if hasattr(obj, attr_name) and getattr(obj, attr_name):
                description = "[[{}|{}]]".format(
                    getattr(obj, attr_name), attr_name.capitalize()
                )
                break

        if obj.full_url:
            description = "[[{}|{}]]".format(obj.full_url, _("Homepage"))

        if obj.email:
            description += "\n[[mailto:{}|{}]]".format(obj.email, obj.email)

        features.append(
            {
                "type": "Feature",
                "properties": {
                    "name": name,
                    "description": description,
                    "_umap_options": {},
                },
                "geometry": {
                    "type": "Point",
                    "coordinates": [obj.lnglat.split(",")[0], obj.lnglat.split(",")[1]],
                },
            }
        )

    icon_url = request.build_absolute_uri(static("img/extinctionsymbol_48.png"))

    data = {
        "type": "FeatureCollection",
        "features": features,
        "_umap_options": {"iconURL": icon_url},
    }

    return JsonResponse(data)

src/xr_embeds/templates/xr_embeds/blocks/gdpr_embed.html
{% extends "xr_pages/blocks/base.html" %}
{% load i18n %}
{% load wagtailcore_tags %}
{% load xr_embed_tags %}


{% block block_content %}

    {% get_embed value.embed.url as embed %}

    <div class="embed-wrapper" style="{% if value.width %}width: {{ value.width }}; {% endif %}{% if value.height %}height: {{ value.height }};{% endif %}">

    {% if value.show_gdpr_message %}

        {% if embed.thumbnail_url %}
            {% get_cached_image embed.thumbnail_url as cached_image %}
        {% endif %}


            <div data-embed-url="{% url "embeds:embed_html" embed.pk %}"
                 {% if embed.is_responsive %}style="height: 0; padding-bottom: {{ embed.ratio_css }};"{% endif %} class="responsive-object">

                {% if cached_image %}
                    <img class="embed-placeholder" src="{{ cached_image.url }}" alt="{{ embed.title|escape }}">
                {% else %}
                    <div class="embed-placeholder"></div>
                {% endif %}

                <div class="embed-load-message">
                    <p>
                        {% blocktrans trimmed with provider=embed.provider_name %}
                            This content will be loaded from "{{ provider }}".
                        {% endblocktrans %}
                    </p>
                    <button type="button" class="embed-load-button">
                        {% trans "Load Content." %}
                    </button>
                </div>

            </div>


    {% else %}
        <div {% if embed.is_responsive %} style="height: 0; padding-bottom: {{ embed.ratio_css }};"{% endif %} class="responsive-object">

            {{ embed.html|safe }}

        </div>

    {% endif %}

    </div>

{% endblock %}